#!/usr/bin/python3

import os, sys, getopt, shutil

arguments_input = sys.argv[1:]
options = "h"
long_options = ['run=', 'reports-dir=', 'logs-dir=']

def deleteFolders(reports_dir, logs_dir):
    os.system(f'rm -rf ./{reports_dir}')
    os.system(f'rm -rf ./{logs_dir}')

try:
    arguments, values = getopt.getopt(arguments_input, options, long_options)

    # default values
    run = 'unittests'
    reports_dir = 'reports'
    logs_dir = 'logs'

    # delete default folders
    os.system('rm -rf ./build')
    deleteFolders(reports_dir, logs_dir)

    # read arguments
    for current_argument, current_value in arguments:
        if current_argument in ('-h'):
            print('Usage:')
            print('--run <unittests|integrationtests>: default is unittests')
            print('--reports-dir <dir>: default is reports')
            quit
        if current_argument in ('--run'):
            run = current_value
        elif current_argument in ('--reports-dir'):
            reports_dir = current_value

    # define class to be executed
    test_target = ''
    if run == 'unittests':
        test_target = 'SimpleCalcTest'
    elif run == 'integrationtests':
        test_target = 'it.Runner'
    else:
        print('Couldn\'t identify run parameter')
        exit -1

    # delete parameterized folders
    deleteFolders(reports_dir, logs_dir)

    # invoke test
    exec_line = f'./gradlew test --tests {test_target} -Dlogs-dir=logs'
    os.system(exec_line)

    # copy reports to destination
    shutil.copytree('build/reports/tests/test', f'{reports_dir}', symlinks=False, ignore=None, copy_function=shutil.copy2, ignore_dangling_symlinks=False, dirs_exist_ok=False)

except getopt.error as err:
    print(str(err))

